"""
IComponent Interface
====================

Generated by InterfaceDesigner
Defines the contract for Component implementations.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional


class IComponent(ABC):
    """
    Interface for Component

    All implementations must provide these methods.
    """

    @abstractmethod
    def process(self, *args, **kwargs) -> Any:
        """
        Process operation

        Implementations must define this method.
        """
        pass

    @abstractmethod
    def validate(self, *args, **kwargs) -> Any:
        """
        Validate operation

        Implementations must define this method.
        """
        pass

    @abstractmethod
    def configure(self, *args, **kwargs) -> Any:
        """
        Configure operation

        Implementations must define this method.
        """
        pass


class ComponentBase(IComponent):
    """
    Base implementation of IComponent

    Provides default implementations where appropriate.
    """

    def __init__(self):
        self._initialized = False

    def process(self, *args, **kwargs) -> Any:
        """Default process implementation"""
        raise NotImplementedError("Subclass must implement process")

    def validate(self, *args, **kwargs) -> Any:
        """Default validate implementation"""
        raise NotImplementedError("Subclass must implement validate")

    def configure(self, *args, **kwargs) -> Any:
        """Default configure implementation"""
        raise NotImplementedError("Subclass must implement configure")
